### ISSUE TITLE
Cannot install zipsign

### ISSUE THREAD

**Issue by jqnatividad** [Kijewski/zipsign#11]
I tried installing it per the README:

`cargo install --git https://github.com/Kijewski/zipsign`

and also after cloning it locally:

`cardo install --path .`

and I get this error for both:

```
error[E0425]: cannot find value `transparent` in this scope
  --> api/src/verify/tar.rs:28:17
   |
28 |         #[error(transparent)]
   |                 ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `transparent` in this scope
  --> api/src/verify/zip.rs:13:17
   |
13 |         #[error(transparent)]
   |                 ^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `zipsign-api` (lib) due to 2 previous errors
```

OS: macOS Sonoma v14.0
Rust: v1.73.0

**Comment by Kijewski** [comment]
Thank you for reporting the issue! It should be fixed now. Could you please test it again? I'll release it to crates.io afterwards.

**Comment by jqnatividad** [comment]
Hi @Kijewski,

Can confirm that it works for me now.  Will be using it for the qsv 0.118.0 release tomorrow... 🤞   will keep you posted!
