### ISSUE TITLE
Add ability to remove signature

### ISSUE THREAD

**Issue by jqnatividad** [Kijewski/zipsign#17]
Hi @Kijewski , I started using zipsign and it's working quite well, EXCEPT when I try to add additional binaries to an already zipsigned archive. Detailed scenario below:

In my project, I publish multiple binaries in a GH action workflow using Rust stable where I zip all the binary variants together, and then sign them with zipsign.

https://github.com/jqnatividad/qsv/blob/master/.github/workflows/publish.yml

and it works!
https://github.com/jqnatividad/qsv/actions/runs/6667825852

In a separate "publish-nightly" workflow, I compile with Rust nightly, download the existing Rust stable zipsigned archive for that platform, and then ADD the nightly binary variants to the existing zipsigned archive.

https://github.com/jqnatividad/qsv/blob/master/.github/workflows/publish-nightly.yml

It used to work before, but now, it doesn't as 7z errors out when it tries to add the nightly binaries to the zipsigned archive:
https://github.com/jqnatividad/qsv/actions/runs/6669133903/job/18126246849

I'm thinking, the easiest way to handle this is to add a subcommand to zipsign to remove a signature.
And then I add the additional nightly binaries to the now unsigned zip archive.
And then zipsign it again.

WDYT?

**Comment by Kijewski** [comment]
Thank you for the suggestion. Implemented in v0.1.1.
